name = "Portal 2"
home = "https://discord.com/channels/731205301247803413/1172548724921208852"
default_url = "https://github.com/GlassToadstool/Archipelago/releases/download/{{version}}/portal2.apworld"

[versions]
"0.2.0" = { url = "https://github.com/GlassToadstool/Archipelago/releases/download/0.2/portal2.apworld" }
